import { NextRequest, NextResponse } from 'next/server';
import { getRed } from '@/lib/red';

interface RouteContext {
  params: Promise<{
    id: string;
  }>;
}

/**
 * GET /api/v1/conversations/[id]/title
 * Fetch the conversation title from Redis (generated by redbtn)
 */
export async function GET(
  _request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const red = await getRed();
    const title = await red.getConversationTitle(id);

    return NextResponse.json({ 
      conversationId: id,
      title: title || null 
    });
  } catch (error) {
    console.error('Error fetching conversation title:', error);
    return NextResponse.json(
      {
        error: {
          message: error instanceof Error ? error.message : 'Internal server error',
          type: 'internal_error',
          code: 'internal_error'
        }
      },
      { status: 500 }
    );
  }
}

/**
 * PUT /api/v1/conversations/[id]/title
 * Set a custom title for the conversation (user override)
 */
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    const { id } = await context.params;
    const body = await request.json();

    if (!body.title || typeof body.title !== 'string') {
      return NextResponse.json(
        {
          error: {
            message: 'title is required and must be a string',
            type: 'invalid_request_error',
            code: 'invalid_title'
          }
        },
        { status: 400 }
      );
    }

    const red = await getRed();
    await red.setConversationTitle(id, body.title);

    return NextResponse.json({ 
      conversationId: id,
      title: body.title,
      titleSetByUser: true
    });
  } catch (error) {
    console.error('Error setting conversation title:', error);
    return NextResponse.json(
      {
        error: {
          message: error instanceof Error ? error.message : 'Internal server error',
          type: 'internal_error',
          code: 'internal_error'
        }
      },
      { status: 500 }
    );
  }
}
