import { NextRequest, NextResponse } from 'next/server';
import { getRed, getDatabase } from '@/lib/red';
import { verifyAuth } from '@/lib/auth/auth';

interface RouteContext {
  params: Promise<{
    id: string;
  }>;
}

/**
 * Helper to verify conversation ownership
 */
async function verifyConversationAccess(conversationId: string, userId: string): Promise<{ allowed: boolean; error?: string }> {
  const db = getDatabase();
  const conversation = await db.getConversation(conversationId);
  if (!conversation) {
    return { allowed: false, error: 'Conversation not found' };
  }
  if (conversation.userId && conversation.userId !== userId) {
    return { allowed: false, error: 'Forbidden' };
  }
  return { allowed: true };
}

/**
 * GET /api/v1/conversations/[id]/title
 * Fetch the conversation title from Redis (generated by redbtn)
 */
export async function GET(
  request: NextRequest,
  context: RouteContext
) {
  try {
    // Verify authentication
    const user = await verifyAuth(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = await context.params;

    // Verify ownership
    const access = await verifyConversationAccess(id, user.userId);
    if (!access.allowed) {
      return NextResponse.json({ error: access.error }, { status: access.error === 'Forbidden' ? 403 : 404 });
    }

    const red = await getRed();
    const title = await red.getConversationTitle(id);

    return NextResponse.json({ 
      conversationId: id,
      title: title || null 
    });
  } catch (error) {
    console.error('Error fetching conversation title:', error);
    return NextResponse.json(
      {
        error: {
          message: error instanceof Error ? error.message : 'Internal server error',
          type: 'internal_error',
          code: 'internal_error'
        }
      },
      { status: 500 }
    );
  }
}

/**
 * PUT /api/v1/conversations/[id]/title
 * Set a custom title for the conversation (user override)
 */
export async function PUT(
  request: NextRequest,
  context: RouteContext
) {
  try {
    // Verify authentication
    const user = await verifyAuth(request);
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = await context.params;

    // Verify ownership
    const access = await verifyConversationAccess(id, user.userId);
    if (!access.allowed) {
      return NextResponse.json({ error: access.error }, { status: access.error === 'Forbidden' ? 403 : 404 });
    }

    const body = await request.json();

    if (!body.title || typeof body.title !== 'string') {
      return NextResponse.json(
        {
          error: {
            message: 'title is required and must be a string',
            type: 'invalid_request_error',
            code: 'invalid_title'
          }
        },
        { status: 400 }
      );
    }

    const red = await getRed();
    await red.setConversationTitle(id, body.title);

    return NextResponse.json({ 
      conversationId: id,
      title: body.title,
      titleSetByUser: true
    });
  } catch (error) {
    console.error('Error setting conversation title:', error);
    return NextResponse.json(
      {
        error: {
          message: error instanceof Error ? error.message : 'Internal server error',
          type: 'internal_error',
          code: 'internal_error'
        }
      },
      { status: 500 }
    );
  }
}
